site_name: e

theme:
  name: material
  palette:
    - scheme: slate
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: 'material/brightness-4'
        name: 'Switch to light mode'
    - scheme: default
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: 'material/brightness-7'
        name: 'Switch to dark mode'
  features:
     - content.code.copy
  #  - navigation.tabs
  #  - navigation.top
copyright: Copyright &copy; 2026-2027 MERY Ludovic & Kevin Huet - Lycée Fulbert - Chartres

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search:
      lang: fr
  - mermaid2
  - mkdocs_quiz
